# Author: Authey
# Date: 13/06/2020

from Scales import Scales


class FlowerDance:

    def __init__(self):
        self.name = 'Flower Dance'
        self.sc = Scales(200)

    def generator(self):
        # -------- first bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.g5(1)
        self.sc.a5(2)
        self.sc.modify_time(2)
        # -------- second bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.a5(1)
        self.sc.b5(2)
        self.sc.modify_time(2)
        # -------- third bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(2)
        self.sc.modify_time(2)
        # -------- fourth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # -------- fifth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.g5(1)
        self.sc.a5(2)
        self.sc.modify_time(2)
        # -------- sixth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.a5(1)
        self.sc.b5(2)
        self.sc.modify_time(2)
        # -------- seventh bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(2)
        self.sc.modify_time(2)
        # -------- eighth bar -------- #
        # ---- major ---- #
        self.sc.e6(8)
        self.sc.modify_time(8, 1)
        self.sc.a6(8)
        self.sc.modify_time(8, 1)
        self.sc.c7s(8)
        self.sc.modify_time(8, 1)
        self.sc.e7(8)
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(8)
        self.sc.modify_time(8, 1)
        self.sc.e5(8)
        self.sc.modify_time(8, 1)
        self.sc.a5(8)
        # -------- ninth bar -------- #
        # ---- major ---- #
        self.sc.e6(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(4, 1)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(4, 1)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(7, 1)
        # ---- minor ---- #
        self.sc.c5(2)
        self.sc.modify_time(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(2)
        # -------- tenth bar -------- #
        # ---- major ---- #
        self.sc.b5(1.5)
        self.sc.modify_time(1.5, 1)
        self.sc.d6(1.5)
        self.sc.b6(0.5)
        self.sc.a6(1.5)
        self.sc.g6s(0.5)
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.e7(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e4(1)
        self.sc.b4(1)
        self.sc.e5(1)
        self.sc.g5s(1)
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.e5(1)
        # -------- eleventh bar -------- #
        # ---- major ---- #
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.a6(2)
        self.sc.modify_time(2, 1)
        self.sc.e7(2)
        self.sc.d7(1)
        self.sc.d7(0.333)
        self.sc.e7(0.333)
        self.sc.d7(0.333)
        self.sc.b6(1)
        self.sc.g6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.c5(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- twelfth bar -------- #
        # ---- major ---- #
        self.sc.a6(6)
        self.sc.modify_time(1)
        self.sc.e6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(1)
        self.sc.e5(1)
        self.sc.a5(2)
        # -------- thirteenth bar -------- #
        # ---- major ---- #
        self.sc.a5(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(8, 1)
        self.sc.c6(2.5)
        self.sc.modify_time(1.5)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(8, 1)
        self.sc.e6(2.5)
        self.sc.modify_time(1.5)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(2)
        self.sc.modify_time(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(2)
        # -------- fourteenth bar -------- #
        # ---- major ---- #
        self.sc.b5(1)
        self.sc.b5(1)
        self.sc.modify_time(2, 1)
        self.sc.d6(1)
        self.sc.g6s(1)
        self.sc.a6(1)
        self.sc.b6(1)
        self.sc.e6(0.5)
        self.sc.c7(0.5)
        self.sc.d6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.g6(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e4(1)
        self.sc.b4(1)
        self.sc.e5(2)
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(2)
        # -------- fifteenth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(2)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(2)
        # -------- sixteenth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6s(2)
        self.sc.modify_time(2)
        # -------- seventeenth bar -------- #
        # ---- major ---- #
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.e6(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.d7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.b5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.g6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(1)
        self.sc.e5(1)
        self.sc.e4(1)
        self.sc.b4(1)
        self.sc.e5(2)
        self.sc.modify_time(2, 1)
        self.sc.g5(2)
        # -------- eighteenth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.f6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(1)
        self.sc.c5(1)
        self.sc.c4(1)
        self.sc.g4(1)
        self.sc.c5(2)
        self.sc.modify_time(2, 1)
        self.sc.e5(2)
        # -------- nineteenth bar -------- #
        # ---- major ---- #
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.a5(0.5)
        self.sc.d6(0.5)
        self.sc.a5(0.5)
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(1)
        self.sc.modify_time(1, 1)
        self.sc.d4(1)
        self.sc.a4(1)
        self.sc.f5(0.5)
        self.sc.e5(0.5)
        self.sc.d5(0.5)
        self.sc.c5(0.5)
        self.sc.a2(1)
        self.sc.modify_time(1, 1)
        self.sc.a3(1)
        self.sc.e3(1)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.c4(0.5)
        self.sc.b3(0.5)
        # -------- twentieth bar -------- #
        # ---- major ---- #
        self.sc.d6(0.5)
        self.sc.f5(0.5)
        self.sc.c6(0.5)
        self.sc.f5(0.5)
        self.sc.b5(0.5)
        self.sc.f5(0.5)
        self.sc.a5(0.5)
        self.sc.f5(0.5)
        self.sc.f5(1)
        self.sc.f5(1)
        self.sc.e5(2)
        self.sc.modify_time(4, 1)
        self.sc.g5s(1)
        self.sc.a5(1)
        self.sc.b5(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.b2(1)
        self.sc.modify_time(1, 1)
        self.sc.b3(1)
        self.sc.f4(1)
        self.sc.b4(1)
        self.sc.modify_time(1, 1)
        self.sc.d5(1)
        self.sc.f4(1)
        self.sc.d4(1)
        self.sc.c4(1)
        self.sc.b3(1)
        self.sc.e3(1)
        self.sc.modify_time(4, 1)
        self.sc.d5(1)
        self.sc.c5(1)
        self.sc.b4(1)
        self.sc.e4(1)
        # -------- twenty-first bar -------- #
        # ---- major ---- #
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.e3(1)
        self.sc.b3(1)
        self.sc.g4(1)
        self.sc.b3(1)
        # -------- twenty-second bar -------- #
        # ---- major ---- #
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.g4(0.5)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.c3(1)
        self.sc.g3(1)
        self.sc.e4(1)
        self.sc.g3(1)
        # -------- twenty-third bar -------- #
        # ---- major ---- #
        self.sc.f5(1)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(1)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(0.5)
        self.sc.a3(0.5)
        self.sc.d4(0.5)
        self.sc.e4(0.5)
        self.sc.f4(0.5)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.a3(0.5)
        self.sc.a2(0.5)
        self.sc.e3(0.5)
        self.sc.a3(0.5)
        self.sc.b3(0.5)
        self.sc.c4(0.5)
        self.sc.d4(0.5)
        self.sc.e4(1)
        # -------- twenty-fourth bar -------- #
        # ---- major ---- #
        self.sc.a5(1)
        self.sc.e6(1)
        self.sc.g5s(1)
        self.sc.e6(1)
        self.sc.a5(4)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(2)
        self.sc.b2(1.5)
        self.sc.a2(0.5)
        self.sc.a2(1)
        self.sc.modify_time(5, 1)
        self.sc.d4(2)
        self.sc.b3(1.5)
        self.sc.a3(0.5)
        self.sc.a3(1)
        self.sc.e4(1)
        self.sc.a4(2)
        # -------- twenty-fifth bar -------- #
        # ---- major ---- #
        self.sc.a5(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(8, 1)
        self.sc.c6(2.5)
        self.sc.modify_time(1.5)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(8, 1)
        self.sc.e6(2.5)
        self.sc.modify_time(1.5)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.modify_time(1, 1)
        self.sc.f4(1)
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.f5(1)
        self.sc.f4(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.modify_time(1, 1)
        self.sc.g5(1)
        self.sc.g4(1)
        # -------- twenty-sixth bar -------- #
        # ---- major ---- #
        self.sc.b5(1.5)
        self.sc.modify_time(1.5, 1)
        self.sc.d6(1.5)
        self.sc.b6(0.5)
        self.sc.a6(1.5)
        self.sc.g6s(0.5)
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.e7(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e3(1)
        self.sc.modify_time(1, 1)
        self.sc.e4(1)
        self.sc.e4(1)
        self.sc.g4s(1)
        self.sc.modify_time(1, 1)
        self.sc.b4(1)
        self.sc.e4(1)
        self.sc.a3(1)
        self.sc.modify_time(1, 1)
        self.sc.a4(1)
        self.sc.e4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.e5(1)
        self.sc.e4(1)
        # -------- twenty-seventh bar -------- #
        # ---- major ---- #
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.a6(2)
        self.sc.modify_time(2, 1)
        self.sc.e7(2)
        self.sc.d7(1)
        self.sc.d7(0.333)
        self.sc.e7(0.333)
        self.sc.d7(0.333)
        self.sc.b6(1)
        self.sc.g6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.modify_time(1, 1)
        self.sc.f4(1)
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.f5(1)
        self.sc.f4(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.modify_time(1, 1)
        self.sc.g5(1)
        self.sc.g4(1)
        # -------- twenty-eighth bar -------- #
        # ---- major ---- #
        self.sc.a6(6)
        self.sc.modify_time(1)
        self.sc.e6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(1)
        self.sc.modify_time(1, 1)
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.a5(1)
        self.sc.modify_time(1, 1)
        self.sc.c6(1)
        self.sc.e5(1)
        self.sc.a5(2)
        # -------- twenty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a5(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(8, 1)
        self.sc.c6(2.5)
        self.sc.modify_time(1.5)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(8, 1)
        self.sc.e6(2.5)
        self.sc.modify_time(1.5)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.modify_time(1, 1)
        self.sc.f4(1)
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.f5(1)
        self.sc.f4(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.modify_time(1, 1)
        self.sc.g5(1)
        self.sc.g4(1)
        # -------- thirtieth bar -------- #
        # ---- major ---- #
        self.sc.b5(1)
        self.sc.b5(1)
        self.sc.modify_time(2, 1)
        self.sc.d6(1)
        self.sc.g6s(1)
        self.sc.a6(1)
        self.sc.b6(1)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.b5(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e3(1)
        self.sc.modify_time(1, 1)
        self.sc.e4(1)
        self.sc.e4(1)
        self.sc.g4s(1)
        self.sc.modify_time(1, 1)
        self.sc.b4(1)
        self.sc.e4(1)
        self.sc.a3(1)
        self.sc.modify_time(1, 1)
        self.sc.a4(1)
        self.sc.e4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.e5(1)
        self.sc.e4(1)
        # -------- thirty-first bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.c4(1)
        self.sc.f4(2)
        self.sc.modify_time(2, 1)
        self.sc.a4(2)
        self.sc.g3(1)
        self.sc.d4(1)
        self.sc.g4(2)
        self.sc.modify_time(2, 1)
        self.sc.b4(2)
        # -------- thirty-second bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(1)
        self.sc.e4(1)
        self.sc.a4(1)
        self.sc.b4(1)
        self.sc.c5s(3)
        self.sc.a4(1)
        # -------- thirty-third bar -------- #
        # ---- major ---- #
        self.sc.a5(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(8, 1)
        self.sc.c6(2.5)
        self.sc.modify_time(1.5)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(8, 1)
        self.sc.e6(2.5)
        self.sc.modify_time(1.5)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.modify_time(1, 1)
        self.sc.f4(1)
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.f5(1)
        self.sc.f4(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.b4(0.5)
        self.sc.d5(0.5)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- thirty-fourth bar -------- #
        # ---- major ---- #
        self.sc.b5(1.5)
        self.sc.modify_time(1.5, 1)
        self.sc.d6(1.5)
        self.sc.b6(0.5)
        self.sc.a6(1.5)
        self.sc.g6s(0.5)
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.e7(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e3(1)
        self.sc.modify_time(1, 1)
        self.sc.e4(1)
        self.sc.e4(1)
        self.sc.g4s(1)
        self.sc.modify_time(1, 1)
        self.sc.b4(1)
        self.sc.e4(1)
        self.sc.a3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(1)
        self.sc.a5(1)
        # -------- thirty-fifth bar -------- #
        # ---- major ---- #
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.a6(2)
        self.sc.modify_time(2, 1)
        self.sc.e7(2)
        self.sc.d7(1)
        self.sc.d7(0.333)
        self.sc.e7(0.333)
        self.sc.d7(0.333)
        self.sc.b6(1)
        self.sc.g6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.modify_time(1, 1)
        self.sc.g5(1)
        self.sc.g4(1)
        # -------- thirty-sixth bar -------- #
        # ---- major ---- #
        self.sc.a6(6)
        self.sc.modify_time(1)
        self.sc.e6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.b5(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.c5(1)
        self.sc.a4(1)
        # -------- thirty-seventh bar -------- #
        # ---- major ---- #
        self.sc.a5(2.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.g5(2)
        self.sc.b5(2)
        self.sc.modify_time(8, 1)
        self.sc.c6(2.5)
        self.sc.modify_time(1.5)
        self.sc.b5(2)
        self.sc.d6(2)
        self.sc.modify_time(8, 1)
        self.sc.e6(2.5)
        self.sc.modify_time(1.5)
        self.sc.d6(2)
        self.sc.g6(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(1)
        self.sc.modify_time(1, 1)
        self.sc.f4(1)
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.f5(1)
        self.sc.f4(1)
        self.sc.g3(1)
        self.sc.modify_time(1, 1)
        self.sc.g4(1)
        self.sc.b4(0.5)
        self.sc.d5(0.5)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- thirty-eighth bar -------- #
        # ---- major ---- #
        self.sc.b5(1.5)
        self.sc.modify_time(1.5, 1)
        self.sc.d6(1.5)
        self.sc.b6(0.5)
        self.sc.a6(1.5)
        self.sc.g6s(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.b5(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.e3(1)
        self.sc.modify_time(1, 1)
        self.sc.e4(1)
        self.sc.e4(1)
        self.sc.g4s(1)
        self.sc.modify_time(1, 1)
        self.sc.b4(1)
        self.sc.e4(1)
        self.sc.a3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(1)
        self.sc.e5(1)
        # -------- thirty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.d7(0.5)
        self.sc.e7(0.5)
        # time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(1)
        self.sc.c4(1)
        self.sc.g3(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(1)
        self.sc.d4(1)
        # -------- fortieth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(0.5)
        self.sc.e7(0.5)
        self.sc.c7s(0.5)
        self.sc.e7(0.5)
        self.sc.a6(1)
        self.sc.e6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5s(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.b5(0.5)
        self.sc.c6(2)
        self.sc.e4(2)
        self.sc.modify_time(2, 1)
        self.sc.e5(2)
        # -------- forty-first bar -------- #
        # ---- major ---- #
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.e6(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.d7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.b5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.g6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.d5(0.5)
        self.sc.e5(1)
        self.sc.e3(1)
        self.sc.modify_time(1, 1)
        self.sc.e4(1)
        self.sc.b4(1)
        self.sc.e5(1)
        self.sc.modify_time(1, 1)
        self.sc.g5(1)
        self.sc.b4(1)
        # -------- forty-second bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.f6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.modify_time(0.5, 1)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(1)
        self.sc.c3(1)
        self.sc.modify_time(1, 1)
        self.sc.c4(1)
        self.sc.g4(1)
        self.sc.c5(1)
        self.sc.modify_time(1, 1)
        self.sc.e5(1)
        self.sc.g4(1)
        # -------- forty-third bar -------- #
        # ---- major ---- #
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.a5(0.5)
        self.sc.d6(0.5)
        self.sc.a5(0.5)
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(1)
        self.sc.modify_time(1, 1)
        self.sc.d4(1)
        self.sc.a4(1)
        self.sc.f5(0.5)
        self.sc.e5(0.5)
        self.sc.d5(0.5)
        self.sc.c5(0.5)
        self.sc.a2(1)
        self.sc.modify_time(1, 1)
        self.sc.a3(1)
        self.sc.e3(1)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.c4(0.5)
        self.sc.b3(0.5)
        # -------- forty-fourth bar -------- #
        # ---- major ---- #
        self.sc.d6(0.5)
        self.sc.f5(0.5)
        self.sc.c6(0.5)
        self.sc.f5(0.5)
        self.sc.b5(0.5)
        self.sc.f5(0.5)
        self.sc.a5(0.5)
        self.sc.f5(0.5)
        self.sc.f5(1)
        self.sc.f5(1)
        self.sc.e5(2)
        self.sc.modify_time(4, 1)
        self.sc.g5s(1)
        self.sc.a5(1)
        self.sc.b5(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.b2(1)
        self.sc.modify_time(1, 1)
        self.sc.b3(1)
        self.sc.f4(1)
        self.sc.b4(1)
        self.sc.modify_time(1, 1)
        self.sc.d5(1)
        self.sc.f4(1)
        self.sc.d4(1)
        self.sc.c4(1)
        self.sc.b3(1)
        self.sc.e3(1)
        self.sc.modify_time(4, 1)
        self.sc.d5(1)
        self.sc.c5(1)
        self.sc.b4(1)
        self.sc.e4(1)
        # -------- forty-fifth bar -------- #
        # ---- major ---- #
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.e3(1)
        self.sc.b3(1)
        self.sc.g4(1)
        self.sc.b3(1)
        # -------- forty-sixth bar -------- #
        # ---- major ---- #
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.g4(0.5)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.c3(1)
        self.sc.g3(1)
        self.sc.e4(1)
        self.sc.g3(1)
        # -------- forty-seventh bar -------- #
        # ---- major ---- #
        self.sc.f5(1)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(1)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(0.5)
        self.sc.a3(0.5)
        self.sc.d4(0.5)
        self.sc.e4(0.5)
        self.sc.f4(0.5)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.a3(0.5)
        self.sc.a2(0.5)
        self.sc.e3(0.5)
        self.sc.a3(0.5)
        self.sc.b3(0.5)
        self.sc.c4(0.5)
        self.sc.d4(0.5)
        self.sc.e4(1)
        # -------- forty-eighth bar -------- #
        # ---- major ---- #
        self.sc.a5(1)
        self.sc.e6(1)
        self.sc.g5s(1)
        self.sc.e6(1)
        self.sc.a5(4)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(2)
        self.sc.b2(1.5)
        self.sc.a2(0.5)
        self.sc.a2(1)
        self.sc.modify_time(5, 1)
        self.sc.d4(2)
        self.sc.b3(1.5)
        self.sc.a3(0.5)
        self.sc.a3(1)
        self.sc.e4(1)
        self.sc.a4(2)
        # -------- forty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f5(2)
        self.sc.f5(2)
        self.sc.g5(2)
        self.sc.e5(2)
        # -------- fiftieth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a5(2)
        self.sc.e5(2)
        self.sc.a4(2)
        self.sc.e5(2)
        # -------- fifty-first bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f5(2)
        self.sc.a5(2)
        self.sc.g5(2)
        self.sc.e5(2)
        # -------- fifty-second bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.d7(0.5)
        self.sc.d6(0.5)
        self.sc.e7(0.5)
        self.sc.e6(0.5)
        self.sc.d7(0.5)
        self.sc.d6(0.5)
        self.sc.c7(2)
        self.sc.a6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a5(2)
        self.sc.e5(2)
        self.sc.c6(2)
        self.sc.e5(2)
        # -------- fifty-third bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f5(4)
        self.sc.g5(2)
        self.sc.e5(2)
        # -------- fifty-fourth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a5(2)
        self.sc.e5(2)
        self.sc.c6(2)
        self.sc.e5(2)
        # -------- fifty-fifth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f5(4)
        self.sc.g5(2)
        self.sc.e5(2)
        # -------- fifty-sixth bar -------- #
        # ---- major ---- #
        self.sc.a6(6)
        self.sc.modify_time(1)
        self.sc.a6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(1)
        self.sc.e5(1)
        self.sc.a5(2)
        # -------- fifty-seventh bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.c5(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- fifty-eighth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.e5(1)
        self.sc.a4(1)
        self.sc.a5(1)
        self.sc.e5(1)
        self.sc.a5(1)
        # -------- fifty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.c5(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- sixtieth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.d7(0.5)
        self.sc.d6(0.5)
        self.sc.e7(0.5)
        self.sc.e6(0.5)
        self.sc.d7(0.5)
        self.sc.d6(0.5)
        self.sc.c7(2)
        self.sc.a6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.e5(1)
        self.sc.a4(1)
        self.sc.a5(1)
        self.sc.e5(1)
        self.sc.a5(1)
        # -------- sixty-first bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.c5(1)
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.d5(1)
        # -------- sixty-second bar -------- #
        # ---- major ---- #
        self.sc.a6(6)
        self.sc.modify_time(1)
        self.sc.a6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(1)
        self.sc.e5(1)
        self.sc.a5(2)
        # -------- sixty-third bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- sixty-fourth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.c6(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.b4(0.5)
        self.sc.a5(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.g4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        # -------- sixty-fifth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- sixty-sixth bar -------- #
        # ---- major ---- #
        self.sc.c6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.c7(0.5)
        self.sc.e7(0.5)
        self.sc.c7(2)
        self.sc.modify_time(2, 1)
        self.sc.e7(2)
        self.sc.modify_time(2, 1)
        self.sc.a7(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.b4(0.5)
        self.sc.a5(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.b5(0.5)
        self.sc.e4(0.5)
        self.sc.b4(0.5)
        self.sc.d5(0.5)
        # -------- sixty-seventh bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- sixty-eighth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.c6(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.b4(0.5)
        self.sc.a5(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.g4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        # -------- sixty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- seventieth bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.c6(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.b4(0.5)
        self.sc.a5(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.g4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        # -------- seventy-first bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- seventy-second bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.b6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.c6(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.b4(0.5)
        self.sc.a5(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.g4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        # -------- seventy-third bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.c6(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.e5(0.5)
        self.sc.a6(0.5)
        self.sc.a5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.d4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.e5(0.5)
        self.sc.b4(0.5)
        self.sc.b5(0.5)
        self.sc.b4(0.5)
        # -------- seventy-fourth bar -------- #
        # ---- major ---- #
        self.sc.c6(2)
        self.sc.modify_time(2, 1)
        self.sc.a6(2)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.a6(0.5)
        self.sc.c7(0.5)
        self.sc.e7(0.5)
        self.sc.c7(6)
        self.sc.modify_time(6, 1)
        self.sc.e7(6)
        self.sc.modify_time(6, 1)
        self.sc.a7(6)
        # ---- time correct ---- #
        self.sc.modify_time(12, 1)
        # ---- minor ---- #
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.a5(0.5)
        self.sc.g4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.c5(0.5)
        self.sc.a4(0.5)
        self.sc.a3(6)
        # -------- seventy-fifth bar -------- #
        # ---- major ---- #
        self.sc.modify_time(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.c7(0.5)
        self.sc.b6(0.5)
        self.sc.a6(0.5)
        self.sc.b6(0.5)
        self.sc.g6s(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(2, 1)
        # ---- minor ---- #
        self.sc.g3s(2)
        self.sc.modify_time(2, 1)
        self.sc.g4s(2)
        # -------- seventy-sixth bar -------- #
        # ---- major ---- #
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.e6(0.5)
        self.sc.c7(0.5)
        self.sc.e6(0.5)
        self.sc.d7(0.5)
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.b5(0.5)
        self.sc.a6(0.5)
        self.sc.b5(0.5)
        self.sc.g6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(1)
        self.sc.modify_time(1, 1)
        self.sc.e5(1)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.b5(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.b4(0.5)
        self.sc.g5(0.5)
        self.sc.g4(0.5)
        self.sc.e3(0.5)
        self.sc.e4(0.5)
        # -------- seventy-seventh bar -------- #
        # ---- major ---- #
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.a6(0.5)
        self.sc.c6(0.5)
        self.sc.c7(0.5)
        self.sc.c6(0.5)
        self.sc.g6(0.5)
        self.sc.c6(0.5)
        self.sc.f6(0.5)
        self.sc.c6(0.5)
        self.sc.e6(1)
        self.sc.e6(0.5)
        self.sc.g6(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a5(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.a4(0.5)
        self.sc.f4(0.5)
        self.sc.g5(0.5)
        self.sc.c4(0.5)
        self.sc.e4(0.5)
        self.sc.g4(0.5)
        self.sc.c5(0.5)
        self.sc.g4(0.5)
        self.sc.e4(0.5)
        self.sc.c4(0.5)
        # -------- seventy-eighth bar -------- #
        # ---- major ---- #
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.a5(0.5)
        self.sc.d6(0.5)
        self.sc.a5(0.5)
        self.sc.f6(0.5)
        self.sc.a5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.e6(0.5)
        self.sc.e5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f5(0.5)
        self.sc.d5(0.5)
        self.sc.a4(0.5)
        self.sc.f4(0.5)
        self.sc.d3(0.5)
        self.sc.d4(0.5)
        self.sc.f4(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.c4(0.5)
        self.sc.a2(0.5)
        self.sc.a3(0.5)
        self.sc.e3(0.5)
        self.sc.c4(0.5)
        # -------- seventy-ninth bar -------- #
        # ---- major ---- #
        self.sc.d6(0.5)
        self.sc.f5(0.5)
        self.sc.c6(0.5)
        self.sc.f5(0.5)
        self.sc.b5(0.5)
        self.sc.f5(0.5)
        self.sc.a5(0.5)
        self.sc.f5(0.5)
        self.sc.f5(1)
        self.sc.f5(1)
        self.sc.e5(2)
        self.sc.modify_time(4, 1)
        self.sc.g5s(1)
        self.sc.a5(1)
        self.sc.b5(2)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.b5(1)
        self.sc.b4(1)
        self.sc.e3(1)
        self.sc.e4(1)
        self.sc.d4(1)
        self.sc.c4(1)
        self.sc.b3(1)
        self.sc.e3(1)
        self.sc.modify_time(4, 1)
        self.sc.d5(1)
        self.sc.c5(1)
        self.sc.b4(1)
        self.sc.e4(1)
        # -------- eightieth bar -------- #
        # ---- major ---- #
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.e3(1)
        self.sc.b3(1)
        self.sc.g4(1)
        self.sc.b3(1)
        # -------- eighty-first bar -------- #
        # ---- major ---- #
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.g4(0.5)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.c3(1)
        self.sc.g3(1)
        self.sc.c4(1)
        self.sc.g3(1)
        # -------- eighty-second bar -------- #
        # ---- major ---- #
        self.sc.f5(1)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(1)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(0.5)
        self.sc.a3(0.5)
        self.sc.d4(0.5)
        self.sc.e4(0.5)
        self.sc.f4(0.5)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.a3(0.5)
        self.sc.a2(0.5)
        self.sc.e3(0.5)
        self.sc.a3(0.5)
        self.sc.b3(0.5)
        self.sc.c4(0.5)
        self.sc.d4(0.5)
        self.sc.e4(1)
        # -------- eighty-third bar -------- #
        # ---- major ---- #
        self.sc.a5(1)
        self.sc.e6(1)
        self.sc.g5s(1)
        self.sc.e6(1)
        self.sc.a5(3)
        self.sc.e5(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(2)
        self.sc.b2(1.5)
        self.sc.a2(0.5)
        self.sc.a2(1)
        self.sc.modify_time(5, 1)
        self.sc.d4(2)
        self.sc.b3(1.5)
        self.sc.a3(0.5)
        self.sc.a3(1)
        self.sc.e4(1)
        self.sc.a4(1)
        self.sc.b4(1)
        # -------- eighty-fourth bar -------- #
        # ---- major ---- #
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(1)
        self.sc.a6(2)
        self.sc.modify_time(2, 1)
        self.sc.c7(2)
        self.sc.e3(0.5)
        self.sc.b3(0.5)
        self.sc.c4(1)
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.g6(1)
        # -------- eighty-fifth bar -------- #
        # ---- major ---- #
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d5(0.5)
        self.sc.a5(0.5)
        self.sc.d6(1)
        self.sc.a6(2)
        self.sc.modify_time(2, 1)
        self.sc.c7(2)
        self.sc.e3(0.5)
        self.sc.b3(0.5)
        self.sc.e4(1)
        self.sc.e6(2)
        self.sc.modify_time(2, 1)
        self.sc.g6(2)
        # -------- eighty-sixth bar -------- #
        # ---- major ---- #
        self.sc.f5(1)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(1)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(0.5)
        self.sc.a3(0.5)
        self.sc.d4(0.5)
        self.sc.f4(0.5)
        self.sc.a4(0.5)
        self.sc.d5(0.5)
        self.sc.a4(0.5)
        self.sc.f4(0.5)
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        # -------- eighty-seventh bar -------- #
        # ---- major ---- #
        self.sc.a5(1)
        self.sc.e6(1)
        self.sc.g5s(1)
        self.sc.e6(1)
        self.sc.a5(3)
        self.sc.e5(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(2)
        self.sc.modify_time(2, 1)
        self.sc.d4(2)
        self.sc.modify_time(2)
        self.sc.e4(1)
        self.sc.b3(1)
        self.sc.g3(2)
        self.sc.modify_time(4, 1)
        self.sc.e5(1)
        self.sc.b4(1)
        self.sc.g4(2)
        # -------- eighty-eighth bar -------- #
        # ---- major ---- #
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.c6(0.5)
        self.sc.e5(0.5)
        self.sc.d6(0.5)
        self.sc.e5(0.5)
        self.sc.b5(0.5)
        self.sc.e5(0.5)
        self.sc.a5(0.5)
        self.sc.e5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a3(0.5)
        self.sc.e4(0.5)
        self.sc.a4(0.5)
        self.sc.b4(0.5)
        self.sc.c5(0.5)
        self.sc.b4(0.5)
        self.sc.a4(0.5)
        self.sc.e4(0.5)
        self.sc.e3(1)
        self.sc.b3(1)
        self.sc.g4(1)
        self.sc.b3(1)
        # -------- eighty-ninth bar -------- #
        # ---- major ---- #
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.a5(0.5)
        self.sc.c5(0.5)
        self.sc.c6(0.5)
        self.sc.c5(0.5)
        self.sc.g5(0.5)
        self.sc.c5(0.5)
        self.sc.f5(0.5)
        self.sc.c5(0.5)
        self.sc.g5(1)
        self.sc.e5(0.5)
        self.sc.g5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f3(0.5)
        self.sc.c4(0.5)
        self.sc.f4(0.5)
        self.sc.g4(0.5)
        self.sc.a4(0.5)
        self.sc.g4(0.5)
        self.sc.f4(0.5)
        self.sc.c4(0.5)
        self.sc.c3(1)
        self.sc.g3(1)
        self.sc.c4(1)
        self.sc.g3(1)
        # -------- ninetieth bar -------- #
        # ---- major ---- #
        self.sc.f5(1)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(1)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.e6(0.5)
        self.sc.f6(0.5)
        self.sc.e6(0.5)
        self.sc.d6(0.5)
        self.sc.c6(0.5)
        self.sc.b5(0.5)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(0.5)
        self.sc.a3(0.5)
        self.sc.d4(0.5)
        self.sc.e4(0.5)
        self.sc.f4(0.5)
        self.sc.e4(0.5)
        self.sc.d4(0.5)
        self.sc.a3(0.5)
        self.sc.a2(0.5)
        self.sc.e3(0.5)
        self.sc.a3(0.5)
        self.sc.b3(0.5)
        self.sc.c4(0.5)
        self.sc.d4(0.5)
        self.sc.e4(1)
        # -------- ninety-first bar -------- #
        # ---- major ---- #
        self.sc.a5(1)
        self.sc.e6(1)
        self.sc.g5s(1)
        self.sc.e6(1)
        self.sc.a5(3)
        self.sc.e5(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.d3(2)
        self.sc.b2(1.5)
        self.sc.a2(0.5)
        self.sc.a2(1)
        self.sc.modify_time(5, 1)
        self.sc.d4(2)
        self.sc.b3(1.5)
        self.sc.a3(0.5)
        self.sc.a3(1)
        self.sc.e4(1)
        self.sc.a4(1)
        self.sc.e4(1)
        # -------- ninety-second bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.g5(1)
        self.sc.a5(2)
        self.sc.modify_time(2)
        # -------- ninety-third bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.a5(1)
        self.sc.b5(2)
        self.sc.modify_time(2)
        # -------- ninety-fourth bar -------- #
        # ---- major ---- #
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(1)
        self.sc.modify_time(1.5, 1)
        self.sc.d7(0.5)
        self.sc.c7(1)
        self.sc.modify_time(1, 1)
        self.sc.e7(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(2)
        self.sc.modify_time(2)
        # -------- ninety-fifth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # -------- ninety-sixth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.f4(1)
        self.sc.c5(1)
        self.sc.f5(1)
        self.sc.g5(1)
        self.sc.a5(2)
        self.sc.modify_time(2)
        # -------- ninety-seventh bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.a5(1)
        self.sc.b5(2)
        self.sc.modify_time(2)
        # -------- ninety-eighth bar -------- #
        # ---- major ---- #
        self.sc.e6(0.5)
        self.sc.b6(0.5)
        self.sc.d6(1)
        self.sc.modify_time(1.5, 1)
        self.sc.d7(0.5)
        self.sc.c7(1)
        self.sc.modify_time(1, 1)
        self.sc.e7(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(2)
        self.sc.modify_time(2)
        # -------- ninety-ninth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.g4(1)
        self.sc.d5(1)
        self.sc.g5(1)
        self.sc.a5(1)
        self.sc.b5(2)
        self.sc.modify_time(2)
        # -------- one hundredth bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # ---- time correct ---- #
        self.sc.modify_time(8, 1)
        # ---- minor ---- #
        self.sc.a4(1)
        self.sc.e5(1)
        self.sc.a5(1)
        self.sc.b5(1)
        self.sc.c6(2)
        self.sc.modify_time(2)
        # -------- one hundred-first bar -------- #
        # ---- major ---- #
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a6(1)
        self.sc.d6(1)
        self.sc.e6(1)
        self.sc.d6(1)
        self.sc.a5(1)
        self.sc.d6(1)
        # -------- one hundred-second bar -------- #
        # ---- major ---- #
        self.sc.d6(8)
        # -------- end -------- #
        with open(self.name, 'wb') as f:
            self.sc.get_midi().writeFile(f)
        return self.name
